---

- name: Print out the VDOM Link existing values.
  ansible.builtin.debug:
    msg: >
      {{ (lookup('url', vdom_link_api_endpoint
      % (vdom.name), validate_certs=false, split_lines=false, headers=fad_api_header) | from_json).get('payload') }}
  loop: "{{ vdom_links }}"
  loop_control:
    loop_var: vdom
    label: "{{ vdom.name }}"
  tags: [debug]

- name: Create new VDOM Link entry if it's not found.
  ansible.builtin.uri:
    method: POST
    url: "{{ vdom_link_api_endpoint | format(vdom.name) }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: |
      {
        "mkey": "{{ vdom.name }}",
        "type": "{{ vdom.type | default('ethernet') }}"
      }
  register: vdom_link_post_results
  loop: "{{ vdom_links }}"
  loop_control:
    loop_var: vdom
    label: "{{ vdom.name }}"
  when: >
    (lookup('url', vdom_link_api_endpoint
    % (vdom.name), validate_certs=false, split_lines=false,
    headers=fad_api_header) | from_json).get('payload').mkey is undefined
  changed_when: "vdom_link_post_results.json.payload == 0"
  failed_when: vdom_link_post_results.json.payload not in [0, -15]

- name: Update VDOM Link entry if it's exist and any of its value is changed.
  ansible.builtin.uri:
    method: PUT
    url: "{{ vdom_link_api_endpoint | format(vdom.name) }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: |
      {
        "mkey": "{{ vdom.name }}",
        "type": "{{ vdom.type | default('ethernet') }}"
      }
  register: vdom_link_put_results
  loop: "{{ vdom_links }}"
  loop_control:
    loop_var: vdom
    label: "{{ vdom.name }}"
  when:
    - (lookup('url', vdom_link_api_endpoint
      % (vdom.name), validate_certs=false, split_lines=false,
      headers=fad_api_header) | from_json).get('payload')['mkey'] is defined
    - (lookup('url', vdom_link_api_endpoint
      % (vdom.name), validate_certs=false, split_lines=false,
      headers=fad_api_header) | from_json).get('payload')['status'] != vdom.status | default('enabled')
  changed_when: "vdom_link_put_results.json.payload == 0"
  failed_when: "vdom_link_put_results.json.payload != 0 and vdom_link_put_results.json.payload != -15"

- name: Print out the VDOM Link values after create/update task.
  ansible.builtin.debug:
    msg: >
      {{ (lookup('url', vdom_link_api_endpoint
      % (vdom.name), validate_certs=false, split_lines=false, headers=fad_api_header) | from_json).get('payload') }}
  loop: "{{ vdom_links }}"
  loop_control:
    loop_var: vdom
    label: "{{ vdom.name }}"
  tags: [debug]
